Allows default and named export for global-setup
thymikee/jest-preset-angular pull request #1659
Opened 2022-06-25 20:11 UTC by rafagsiqueira

## Summary
If someone wants to run another function before calling the global-setup, they can use a named export or a default export for importing the original global-setup function and calling it manually.
## Test plan
Jest already supports default exports for globalSetup functions, so no impact is expected.
## Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

2022-06-25 20:13 UTC, ahnpnl requested changes

2022-06-25 20:13 UTC, ahnpnl commented on src/config/global-setup.ts
> +const GlobalSetup = () => {
```suggestion
const globalSetup = () => {
```

2022-06-25 22:05 UTC, ahnpnl approved these changes
Thanks!

2022-06-25 22:06 UTC, merged

2022-06-25 22:16 UTC, ahnpnl commented
Note that, if you do in your global setup file
```
const globalSetup = require('jest-preset-angular/global-setup');
```
it will try to import this file https://github.com/thymikee/jest-preset-angular/blob/main/global-setup.js

This won't work because this file is CJS file therefore Jest will throw error unless you run test in ESM mode. 

If you run test in CJS mode, you have to do
```
const globalSetup = require('jest-preset-angular/build/config/global-setup');
```

2022-09-27 14:01 UTC, rafagsiqueira commented
I can confirm this works for a typescript module. Thank you!
```
import { globalSetup } from 'jest-preset-angular/build/config/global-setup';

async function setup() {
    await globalSetup();
    (...)
}

export default setup;
```