fix: update for usage with jest 29
thymikee/jest-preset-angular pull request #1765
Opened 2022-09-09 12:41 UTC by CMiksche

## Summary

There is a new Jest version out there and this package won't work with it unless the dependencies get updated. This package is the sole reason users of Angular currently still have to use Jest 28.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2022-09-09 13:32 UTC, ahnpnl requested changes
Please note that, support Jest 29 is a breaking change.

2022-09-09 13:32 UTC, ahnpnl commented on package.json
> +    "jest-environment-jsdom": "^29.0.2",
```suggestion
    "jest-environment-jsdom": "^29.0.0",
```

2022-09-09 13:32 UTC, ahnpnl commented on package.json
> +    "pretty-format": "^29.0.2",
```suggestion
    "pretty-format": "^29.0.0",
```

2022-09-09 13:32 UTC, ahnpnl commented on package.json
> +    "esbuild-wasm": ">=0.15.7",
```suggestion
    "esbuild-wasm": ">=0.13.8",
```

2022-09-09 13:32 UTC, ahnpnl commented on package.json
> +    "@types/node": "^18.7.16",
```suggestion
    "@types/node": "^16.11.58",
```

2022-09-09 13:32 UTC, ahnpnl commented on package.json
> +    "chalk": "^5.0.1",
```suggestion
    "chalk": "^4.1.2",
```

2022-09-09 13:32 UTC, ahnpnl commented on package.json
> +    "execa": "6.1.0",
```suggestion
    "execa": "5.1.1",
```

2022-09-09 13:32 UTC, ahnpnl commented on package.json
> +    "esbuild": ">=0.15.7"
```suggestion
    "esbuild": ">=0.13.8"
```

2022-09-09 13:32 UTC, ahnpnl commented on package.json
> -    "jest": "^28.1.3",
This one should be put as `"jest": "^29.0.2"`

2022-09-09 13:32 UTC, ahnpnl commented on package.json
> +  "version": "12.2.3",
Please revert this, we only change this when we want to release

2022-09-09 14:46 UTC, CMiksche commented
I made the changes you commented

2022-09-09 14:52 UTC, ahnpnl commented on package.json
> +    "eslint-plugin-jest": "^27.0.2",
```suggestion
    "eslint-plugin-jest": "^26.9.0",
```

2022-09-09 14:53 UTC, ahnpnl commented
Please also run `yarn install` to update lock file.

2022-09-09 15:12 UTC, CMiksche commented
> Please also run `yarn install` to update lock file.

Done

2022-09-11 15:43 UTC, merged

2022-10-18 18:32 UTC, barbados-clemens commented
Hi there, has this been released? I don't see any new versions or pre releases with this change? 

Happy to test some jest 29 changes for nrwl/nx