docs: CSS module should be set to undefined
thymikee/jest-preset-angular pull request #2367
Opened 2024-04-02 15:48 UTC by michael-siek

closes: https://github.com/thymikee/jest-preset-angular/issues/2366

2024-04-04 14:22 UTC, dbjorge requested changes
Several `jest-global-mocks.ts` files within projects under `/examples` also feature a null-CSS mock line similar to the one removed from the doc here. @michael-siek, we should update those examples in line with the doc update.

@ahnpnl , those examples already appear to be run as e2e tests within the repo's CI builds; do you agree that updating them would be sufficient e2e testing for this change, or are you looking for something new?

2024-04-04 14:34 UTC, ahnpnl commented
Yes I would say just need to update an existing test in `examples` folder should be sufficient. 

For this common test, let's try to add it to all example apps under `examples` folder. We try to keep all the tests in those example apps identical to make it easy to migrate to a new major version.

2024-04-10 21:08 UTC, ahnpnl commented
Only small thing, would you please also update similar files at https://github.com/thymikee/jest-preset-angular/tree/main/website/versioned_docs? We have several versioned docs which need to be updated too

2024-04-14 13:33 UTC, ahnpnl approved these changes

2024-04-14 13:33 UTC, merged